version: '3.8'

services:
  whatsapp-service:
    container_name: whatsapp-service
    build: .
    # image: chrishubert/whatsapp-web-api:latest # Pull the image from Docker Hub
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - API_KEY=${API_KEY:-your_global_api_key_here} # OPTIONAL
      - PORT=${PORT:-3000}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:-http://localhost:3000/localCallbackExample}
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
      - SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      - ALL_CALLBACKS=auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - DISABLED_CALLBACKS=${DISABLED_CALLBACKS:-message_ack|message_reactio}
      - ENABLE_SWAGGER_ENDPOINT=${ENABLE_SWAGGER_ENDPOINT:-true} # OPTIONAL, ENABLES THE /api-docs ENDPOINT
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SERVICE_NAME=${SERVICE_NAME:-whatsapp-service}
      - OTEL_EXPORTER_SAMPING_PERCENTAGE=${OTEL_EXPORTER_SAMPING_PERCENTAGE:-1}
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
